name:                doctest-discover-hpack
version:             1.0.0
github:              "blmage/doctest-discover-hpack"
license:             MIT
author:              "Benoît Leulliette"
maintainer:          "benoit.leulliette@gmail.com"
copyright:           "2019 Benoît Leulliette"

extra-source-files:
- README.md

category:            Testing
synopsis:            Automatically discovers and runs Doctests, based on the current Hpack configuration.
description:         Please see the README on GitHub at <https://github.com/blmage/doctest-discover-hpack#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- doctest
- filepath
- hpack >= 0.22.0

library:
  source-dirs: src

executables:
  doctest-discover-hpack:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest-discover-hpack

tests:
  doctest-discover-hpack-test:
    main:                Doctest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - doctest-discover-hpack